# Generated by Django 5.0.6 on 2025-01-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_awardtype_awardcount_constructionworker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardcount',
            options={'verbose_name': '表彰情報', 'verbose_name_plural': '表彰一覧'},
        ),
        migrations.AlterModelOptions(
            name='awardtype',
            options={'verbose_name': '表彰内容', 'verbose_name_plural': '表彰一覧'},
        ),
        migrations.AlterModelOptions(
            name='constructionworker',
            options={'verbose_name': '工事作業員情報', 'verbose_name_plural': '工事作業員一覧'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '従業員情報', 'verbose_name_plural': '従業員一覧'},
        ),
        migrations.AlterModelOptions(
            name='workarea',
            options={'verbose_name': '作業エリア', 'verbose_name_plural': '作業エリア一覧'},
        ),
    ]
