# Generated by Django 4.2.17 on 2025-01-25 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_awardcount_options_alter_awardtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardtype',
            options={'verbose_name': '表彰種類', 'verbose_name_plural': '表彰種類'},
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.DateTimeField(default=datetime.datetime.now, verbose_name='作業日')),
                ('construction_number', models.CharField(max_length=200, verbose_name='工事番号')),
                ('free_comment', models.TextField(max_length=500, verbose_name='自由記述欄')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='従業員')),
            ],
            options={
                'verbose_name': 'お客様の声',
                'verbose_name_plural': 'お客様の声一覧',
            },
        ),
    ]
