# Generated by Django 5.0.6 on 2025-01-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_awardcount_options_alter_awardtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardtype',
            options={'verbose_name': '表彰種類', 'verbose_name_plural': '表彰種類'},
        ),
    ]
