# Generated by Django 5.0.6 on 2025-01-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_awardcount_options_alter_awardtype_options_and_more'),
        ('voc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('weight', models.FloatField(default=1.0, verbose_name='重み')),
                ('order', models.PositiveBigIntegerField(verbose_name='順序')),
            ],
            options={
                'verbose_name': '質問内容',
                'verbose_name_plural': '質問内容一覧',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='agegroup',
            options={'verbose_name': '年代', 'verbose_name_plural': '年代一覧'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': '性別', 'verbose_name_plural': '性別一覧'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'アンケート内容', 'verbose_name_plural': 'アンケート一覧'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '工事情報', 'verbose_name_plural': '工事一覧'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question5',
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('receipt_number', 'receipt_date')},
        ),
        migrations.AddField(
            model_name='survey',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voc_app.work', verbose_name='工事'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='work_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.workarea', verbose_name='作業エリア'),
        ),
        migrations.AlterField(
            model_name='work',
            name='receipt_number',
            field=models.IntegerField(verbose_name='受付番号'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='選択肢')),
                ('points', models.IntegerField(default=0, verbose_name='ポイント')),
                ('order', models.PositiveBigIntegerField(verbose_name='順序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.question', verbose_name='質問内容')),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢一覧',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_start_date',
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.choice', verbose_name='選択肢')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.question', verbose_name='質問内容')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.survey', verbose_name='アンケート')),
            ],
            options={
                'verbose_name': 'アンケート回答',
                'verbose_name_plural': 'アンケート回答一覧',
                'unique_together': {('survey', 'question')},
            },
        ),
    ]
