# Generated by Django 5.0.6 on 2025-01-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_app', '0002_question_alter_agegroup_options_alter_gender_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voc_app.work', verbose_name='工事ID'),
        ),
    ]
