"""
Django settings for voc_project project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bc!+)x3^m@x2)h9+6xv)3d51@=ex_6#&-v4xv(o8m_&*x4-drc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'voc_app',
    'employee_app',
    'axes', 
]

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',  # 必ず AuthenticationMiddleware より前に追加
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'voc_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'voc_app/templates'),
            os.path.join(BASE_DIR, 'employee_app/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voc_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 静的ファイルのURLのベースパス
STATIC_URL = 'static/'

# プロジェクト全体で共通の静的ファイルが保存されているディレクトリ（本番環境では通常使用しません）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # プロジェクト直下のstaticディレクトリ
]

# 本番環境でcollectstaticコマンドで集めた静的ファイルの保存場所
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'employee_app.CustomUser'

# ログイン認証
LOGIN_URL = '/employee/'
LOGIN_REDIRECT_URL = '/general/'
LOGOUT_REDIRECT_URL = '/employee/'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# メッセージのレベルを定義
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',  # Bootstrapのクラスに合わせる場合
}

# ブラウザを閉じた際にセッションを削除
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Axes 設定
AXES_ENABLED = True  # Axes を有効化
AXES_FAILURE_LIMIT = 5  # 最大失敗回数
AXES_COOLOFF_TIME = 1  # ロック解除までの時間 (時間単位)
AXES_LOCKOUT_CALLABLE = None  # カスタムロジックを使用しない場合は None
AXES_RESET_ON_SUCCESS = True  # 成功ログイン時に失敗カウントをリセット

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes 用の認証バックエンド
    'django.contrib.auth.backends.ModelBackend',  # Django の標準認証バックエンド
]
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '2661fe38718f83'
EMAIL_HOST_PASSWORD = '85e78962f4dcc0'
EMAIL_PORT = '2525'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 開発用
# EMAIL_HOST = 'あなたのメールサーバー'  # 実際のメールサーバーの設定
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'あなたのメールアドレス'
# EMAIL_HOST_PASSWORD = 'あなたのメールパスワード'

EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '2661fe38718f83'
EMAIL_HOST_PASSWORD = '85e78962f4dcc0'
EMAIL_PORT = '2525'